<a href="https://colab.research.google.com/github/ramirezcarlos292/miaad_python_programming/blob/main/practices/Pr%C3%A1ctica_6_Unidad_1_Manejo_de_librer%C3%ADa_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instrucciones: <br>
Carga el archivo titanic.csv en la carpeta correspondiente de Google drive para realizar los siguientes ejercicios:

**Ejercicio 1: Análisis de la distribución de supervivencia por combinación de sexo y clase del pasajero.**

* Calcula la proporción de supervivencia para cada combinación de 'Sex' y 'Pclass'.
* Identifica qué combinación tuvo la tasa de supervivencia más alta.
* Identifica qué combinación tuvo la tasa de supervivencia más baja.

**Ejercicio 2: Identificación de familias grandes a bordo.**

* Crea una nueva columna 'FamilySize' sumando las columnas 'SibSp' y 'Parch'.
* Considera como "familia grande" a aquellas donde 'FamilySize' es mayor a 3.
* Calcula el número de pasajeros en familias grandes.
* Calcula la proporción de supervivencia entre los pasajeros que pertenecen a familias grandes.

**Ejercicio 3: Segmentación por grupos de edad.**

Clasifica a los pasajeros en las siguientes categorías de edad(tip puede resultar mas sencillo realizarlo con una función):  menor de edad (< 18) y mayor de edad (>=18)

**Ejercicio 4: Comparación entre promedios calculados manualmente y con Pandas.**

* Utiliza NumPy para calcular el promedio de las columnas 'Age' y 'Fare', ignorando valores nulos.
* Compara estos valores con los promedios obtenidos utilizando los métodos nativos de Pandas.
* Verifica que los resultados sean consistentes.

**Ejercicio 5. Creación de intervalos de clase usando NumPy y análisis con Pandas.**

* Divide la columna 'Fare' en 5 intervalos equidistantes utilizando la función numpy.linspace, el estudiante deberá investigar la operación de esta función en python.
* Crea una nueva columna en el DataFrame que asigne a cada pasajero el intervalo correspondiente de su tarifa.
* Calcula el número de pasajeros en cada intervalo utilizando Pandas y la proporción de supervivientes por intervalo.

# Import libraries

In [ ]:
from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
print(os.getcwd())

/content

# Dataset

- Survived: 0 = Dead, 1 = Survived
- Pclass: Ticket class with 1 = 1st class, 2 = 2nd class, 3 = 3rd class
- Sex: Gender of male or female
- Age: Age in years
- SibSp: Number of siblings/spouses aboard the Titanic
- Parch: Number of parents/children aboard the Titanic
- Ticket: Ticket number
- Fare: Passenger fare
- Cabin: Cabin number
- Embarked: Port of Embarkation with C = Cherbourg, Q = Queenstown, S = Southampton

In [ ]:
!wget -P  /content/drive/MyDrive/ClassFiles/ https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv

--2025-08-23 00:37:23--  https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 60302 (59K) [text/plain]
Saving to: ‘/content/drive/MyDrive/ClassFiles/titanic.csv.4’

titanic.csv.4       100%[===================>]  58.89K  --.-KB/s    in 0.01s

2025-08-23 00:37:23 (4.20 MB/s) - ‘/content/drive/MyDrive/ClassFiles/titanic.csv.4’ saved [60302/60302]

In [ ]:
# Read dataframe
df = pd.read_csv('/content/drive/MyDrive/ClassFiles/titanic.csv')
# cambiar orden de columnas
df = df[['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Survived']]
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1
890,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Pclass       891 non-null    int64
 2   Name         891 non-null    object
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    object
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object
 10  Embarked     889 non-null    object
 11  Survived     891 non-null    int64
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.describe()

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Survived
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,2.308642,29.699118,0.523008,0.381594,32.204208,0.383838
std,257.353842,0.836071,14.526497,1.102743,0.806057,49.693429,0.486592
min,1.000000,1.000000,0.420000,0.000000,0.000000,0.000000,0.000000
25%,223.500000,2.000000,20.125000,0.000000,0.000000,7.910400,0.000000
50%,446.000000,3.000000,28.000000,0.000000,0.000000,14.454200,0.000000
75%,668.500000,3.000000,38.000000,1.000000,0.000000,31.000000,1.000000
max,891.000000,3.000000,80.000000,8.000000,6.000000,512.329200,1.000000

# Ejercicio 1:
Análisis de la distribución de supervivencia por combinación de sexo y clase del pasajero.**

In [ ]:
# * Calcula la proporción de supervivencia para cada combinación de 'Sex' y 'Pclass'.
# * Identifica qué combinación tuvo la tasa de supervivencia más alta.
# * Identifica qué combinación tuvo la tasa de supervivencia más baja.
# como le hacemos? https://statsthinking21.github.io/statsthinking21-core-spanish-site/modeling-categorical-relationships.html
df['Pclass'] = df['Pclass'].astype(str)
df['Sex&Pclass'] = df['Sex'] + df['Pclass']

ej1 = df.copy()
ej1 = ej1[['Sex&Pclass', 'Survived']]
ej1 = ej1.groupby(by='Sex&Pclass').value_counts()

lst = pd.DataFrame(
    {"total_sex&pclass":
     [ej1['female1'].sum(), ej1['female1'].sum(),
      ej1['female2'].sum(), ej1['female2'].sum(),
      ej1['female3'].sum(), ej1['female3'].sum(),
      ej1['male1'].sum(), ej1['male1'].sum(),
      ej1['male2'].sum(), ej1['male2'].sum(),
      ej1['male3'].sum(), ej1['male3'].sum()]
     })

ej1
ej1 = ej1.reset_index()

ej1 = pd.concat([ej1, lst], axis=1)
ej1['Survival_rate_%'] = ej1['count'] / ej1['total_sex&pclass'] * 100

ej1 = ej1.loc[ej1['Survived'] == 1]
ej1

   Sex&Pclass  Survived  count  total_sex&pclass  Survival_rate_%
0     female1         1     91                94        96.808511
2     female2         1     70                76        92.105263
5     female3         1     72               144        50.000000
7       male1         1     45               122        36.885246
9       male2         1     17               108        15.740741
11      male3         1     47               347        13.544669

In [ ]:
print(f"La combinacion con tasa de supervivencia más alta fue: Pasajeros Mujeres de Primera Clase con 96.80% de supervivencia")
ej1.loc[ej1['Survival_rate_%'].idxmax()]

La combinacion con tasa de supervivencia más alta fue: Pasajeros Mujeres de Primera Clase con 96.80% de supervivencia

Sex&Pclass            female1
Survived                    1
count                      91
total_sex&pclass           94
Survival_rate_%     96.808511
Name: 0, dtype: object

In [ ]:
print(f"La combinacion con tasa de supervivencia más baja fue: Pasajeros Hombres de Tercera Clase con 13.54% de supervivencia")
ej1.loc[ej1['Survival_rate_%'].idxmin()]

La combinacion con tasa de supervivencia más baja fue: Pasajeros Hombres de Tercera Clase con 13.54% de supervivencia

Sex&Pclass              male3
Survived                    1
count                      47
total_sex&pclass          347
Survival_rate_%     13.544669
Name: 11, dtype: object

# Ejercicio 2:
Identificación de familias grandes a bordo.**

In [ ]:
# * Crea una nueva columna 'FamilySize' sumando las columnas 'SibSp' y 'Parch'.
# * Considera como "familia grande" a aquellas donde 'FamilySize' es mayor a 3.
# * Calcula el número de pasajeros en familias grandes.
# * Calcula la proporción de supervivencia entre los pasajeros que pertenecen a familias grandes.
ej2 = df.copy()
ej2['FamilySize'] = ej2['SibSp'] + ej2['Parch']
ej2['BigFamily'] = ej2['FamilySize'] > 3
ej2 = ej2[['Survived', 'BigFamily']]

ej2 = ej2.groupby(by='BigFamily').value_counts()
ej2 = ej2.reset_index()
ej2 = ej2.loc[ej2['BigFamily'] == True]
total = ej2['count'].sum()
ej2['Survival_rate'] = ej2['count'] / total * 100
print(f"Survival Rate for people who had big families a bordo fue de: 16.13%")
ej2['Survival_rate'].loc[ej2['Survived'] == 1]

Survival Rate for people who had big families a bordo fue de: 16.13%

3    16.129032
Name: Survival_rate, dtype: float64

# Ejercicio 3:
Segmentación por grupos de edad.

In [ ]:
# Clasifica a los pasajeros en las siguientes categorías de edad(tip puede resultar mas sencillo realizarlo con una función): menor de edad (< 18) y mayor de edad (>=18)
def under_age(value):
  if value < 18:
    return 'menor de edad'
  else:
    return 'mayor de edad'

ej3 = df.copy()
ej3['GroupAge'] = ej3['Age'].apply(under_age)
ej3['GroupAge'].value_counts().reset_index()

        GroupAge  count
0  mayor de edad    778
1  menor de edad    113

# Ejercicio 4:
Comparación entre promedios calculados manualmente y con Pandas.

In [ ]:
# Utiliza NumPy para calcular el promedio de las columnas 'Age' y 'Fare', ignorando valores nulos.
# Compara estos valores con los promedios obtenidos utilizando los métodos nativos de Pandas.
# Verifica que los resultados sean consistentes.
np_age_array = np.array(df['Age'])
np_age_array = np_age_array[~np.isnan(np_age_array)]
print(f"Numpy Age Mean: {float(np_age_array.mean()):.6f}")

np_fare_array = np.array(df['Fare'])
np_fare_array = np_fare_array[~np.isnan(np_fare_array)]
print(f"Numpy Age Fare: {float(np_fare_array.mean()):.6f}")

# Mean Age and Fare using pandas methods
pd.concat([df[['Age']].dropna().mean(), df[['Fare']].dropna().mean()])

Numpy Age Mean: 29.699118
Numpy Age Fare: 32.204208

Age     29.699118
Fare    32.204208
dtype: float64

# Ejercicio 5.
Creación de intervalos de clase usando NumPy y análisis con Pandas.

In [ ]:
# Divide la columna 'Fare' en 5 intervalos equidistantes utilizando la función numpy.linspace, el estudiante deberá investigar la operación de esta función en python.
# Crea una nueva columna en el DataFrame que asigne a cada pasajero el intervalo correspondiente de su tarifa.
# Calcula el número de pasajeros en cada intervalo utilizando Pandas y la proporción de supervivientes por intervalo.

ej5 = df.copy()
minn = min(ej5['Fare'])
maxx = max(ej5['Fare'])
intervalo = np.linspace(minn, maxx, num=5)

def agrupar_tarifa(fare):
  if fare <= intervalo[1]:
    return 'tarifa4'
  elif (fare > intervalo[1]) & (fare <= intervalo[2]):
    return 'tarifa3'
  elif (fare > intervalo[2]) & (fare <= intervalo[3]):
    return 'tarifa2'
  else:
    return 'tarifa1'

ej5['Fare_agrupado'] = ej5['Fare'].apply(agrupar_tarifa)
# Contar total de pasajeros de cada tarifa
s = ej5['Fare_agrupado'].value_counts()
s = s.reset_index()
s = s.rename(columns={'count':'total'})

# Contar solo los pasajeros sobrevivientes por tarifa
ej5 = ej5.loc[ej5['Survived'] == 1]
ej5 = ej5[['Survived', 'Fare_agrupado']]
ej5 = ej5.groupby(by='Fare_agrupado').value_counts()
ej5 = ej5.reset_index()

# Calcular la proporcion de sobrevivientes por intervalo
final = pd.merge(ej5, s, how='left', on='Fare_agrupado')
final['Survival_rate_%'] = final['count'] / final['total'] * 100

final

  Fare_agrupado  Survived  count  total  Survival_rate_%
0       tarifa1         1      3      3       100.000000
1       tarifa2         1      4      6        66.666667
2       tarifa3         1     21     29        72.413793
3       tarifa4         1    314    853        36.811254